# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

module Pangea
  module Resources
    module Hcloud
      include HcloudCertificate
      include HcloudFirewall
      include HcloudFirewallAttachment
      include HcloudFloatingIp
      include HcloudFloatingIpAssignment
      include HcloudLoadBalancer
      include HcloudLoadBalancerNetwork
      include HcloudLoadBalancerService
      include HcloudLoadBalancerTarget
      include HcloudManagedCertificate
      include HcloudNetwork
      include HcloudNetworkRoute
      include HcloudNetworkSubnet
      include HcloudPlacementGroup
      include HcloudPrimaryIp
      include HcloudRdns
      include HcloudServer
      include HcloudServerNetwork
      include HcloudSnapshot
      include HcloudSshKey
      include HcloudStorageBox
      include HcloudStorageBoxSnapshot
      include HcloudStorageBoxSubaccount
      include HcloudUploadedCertificate
      include HcloudVolume
      include HcloudVolumeAttachment
      include HcloudZone
      include HcloudZoneRecord
      include HcloudZoneRrset
    end
  end
end
