# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_volume_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudVolumeAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_volume_attachment,
      attributes_class: Hcloud::Types::VolumeAttachmentAttributes,
      outputs: { id: :id },
      map: [:server_id, :volume_id]
  end
  module Hcloud
    include HcloudVolumeAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
