# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class VolumeAttachmentAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :server_id, (T::Coercible::Integer | T::Coercible::Float)
    attribute :volume_id, (T::Coercible::Integer | T::Coercible::Float)
    attribute? :automount, T::Bool.optional
  end
end
