# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_server_network/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudServerNetwork
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_server_network,
      attributes_class: Hcloud::Types::ServerNetworkAttributes,
      outputs: { id: :id },
      map: [:server_id],
      map_present: [:subnet_id]
  end
  module Hcloud
    include HcloudServerNetwork
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
