# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class ServerNetworkAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :server_id, (T::Coercible::Integer | T::Coercible::Float)
    attribute? :alias_ips, T::Array.of(T::String).optional
    attribute? :ip, T::String.optional
    attribute? :network_id, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :subnet_id, T::String.optional
  end
end
