# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_zone infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_zone/ -t hcloud://

control 'hcloud_zone-exists' do
  impact 1.0
  title 'Manages a hcloud_zone resource'
  desc 'Verify that the hcloud_zone resource exists and has expected properties'

  describe hcloud_zone(name: attribute('id')) do
    it { should exist }
    its('mode') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
