# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_floating_ip/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudFloatingIp
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_floating_ip,
      attributes_class: Hcloud::Types::FloatingIpAttributes,
      outputs: { id: :id },
      map: [:type],
      map_present: [:description, :home_location, :labels, :name, :server_id],
      map_bool: [:delete_protection]
  end
  module Hcloud
    include HcloudFloatingIp
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
