# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class FloatingIpAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :type, T::String
    attribute? :delete_protection, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :home_location, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :name, T::String.optional
    attribute? :server_id, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
