# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_load_balancer_target/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudLoadBalancerTarget
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_load_balancer_target,
      attributes_class: Hcloud::Types::LoadBalancerTargetAttributes,
      outputs: { id: :id },
      map: [:load_balancer_id, :type],
      map_present: [:ip, :label_selector, :server_id]
  end
  module Hcloud
    include HcloudLoadBalancerTarget
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
