# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class LoadBalancerTargetAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :load_balancer_id, T::String
    attribute :type, T::String
    attribute? :ip, T::String.optional
    attribute? :label_selector, T::String.optional
    attribute? :server_id, T::String.optional
  end
end
