# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class LoadBalancerTargetAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :load_balancer_id, (T::Coercible::Integer | T::Coercible::Float)
    attribute :type, T::String
    attribute? :ip, T::String.optional
    attribute? :label_selector, T::String.optional
    attribute? :server_id, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :use_private_ip, T::Bool.optional
  end
end
