# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_primary_ip/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudPrimaryIp
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_primary_ip,
      attributes_class: Hcloud::Types::PrimaryIpAttributes,
      outputs: { id: :id },
      map: [:assignee_type, :type],
      map_present: [:assignee_id, :datacenter, :labels, :location, :name],
      map_bool: [:auto_delete, :delete_protection]
  end
  module Hcloud
    include HcloudPrimaryIp
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
