# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class PrimaryIpAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :assignee_type, T::String
    attribute :auto_delete, T::Bool
    attribute :type, T::String
    attribute? :delete_protection, T::Bool.optional
    attribute? :labels, T::Hash.optional
  end
end
