# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class PrimaryIpAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :assignee_type, T::String
    attribute :auto_delete, T::Bool
    attribute :type, T::String
    attribute? :assignee_id, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :datacenter, T::String.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :labels, T::Hash.optional
    attribute? :location, T::String.optional
    attribute? :name, T::String.optional
  end
end
