# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_placement_group/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudPlacementGroup
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_placement_group,
      attributes_class: Hcloud::Types::PlacementGroupAttributes,
      outputs: { id: :id },
      map: [:name, :type],
      map_present: [:labels]
  end
  module Hcloud
    include HcloudPlacementGroup
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
