# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_zone_record/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudZoneRecord
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_zone_record,
      attributes_class: Hcloud::Types::ZoneRecordAttributes,
      outputs: { id: :id },
      map: [:name, :type, :value, :zone],
      map_present: [:comment]
  end
  module Hcloud
    include HcloudZoneRecord
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
