# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class ZoneRecordAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :name, T::String
    attribute :type, T::String
    attribute :value, T::String
    attribute :zone, T::String
    attribute? :comment, T::String.optional
  end
end
