# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_certificate/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudCertificate
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_certificate,
      attributes_class: Hcloud::Types::CertificateAttributes,
      outputs: { id: :id },
      map: [:certificate, :name, :private_key],
      map_present: [:labels]
  end
  module Hcloud
    include HcloudCertificate
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
