# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_uploaded_certificate infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_uploaded_certificate/ -t hcloud://

control 'hcloud_uploaded_certificate-exists' do
  impact 1.0
  title 'Manages a hcloud_uploaded_certificate resource'
  desc 'Verify that the hcloud_uploaded_certificate resource exists and has expected properties'

  describe hcloud_uploaded_certificate(name: attribute('id')) do
    it { should exist }
    its('certificate') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
