# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_network/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudNetwork
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_network,
      attributes_class: Hcloud::Types::NetworkAttributes,
      outputs: { id: :id },
      map: [:ip_range, :name],
      map_present: [:labels],
      map_bool: [:delete_protection, :expose_routes_to_vswitch]
  end
  module Hcloud
    include HcloudNetwork
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
