# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class NetworkAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :ip_range, T::String
    attribute :name, T::String
    attribute? :delete_protection, T::Bool.optional
    attribute? :expose_routes_to_vswitch, T::Bool.optional
    attribute? :labels, T::Hash.optional
  end
end
