# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_snapshot/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudSnapshot
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_snapshot,
      attributes_class: Hcloud::Types::SnapshotAttributes,
      outputs: { id: :id },
      map: [:server_id],
      map_present: [:description, :labels]
  end
  module Hcloud
    include HcloudSnapshot
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
