# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class SnapshotAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :server_id, (T::Coercible::Integer | T::Coercible::Float)
    attribute? :description, T::String.optional
    attribute? :labels, T::Hash.optional
  end
end
