# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_load_balancer infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_load_balancer/ -t hcloud://

control 'hcloud_load_balancer-exists' do
  impact 1.0
  title 'Manages a hcloud_load_balancer resource'
  desc 'Verify that the hcloud_load_balancer resource exists and has expected properties'

  describe hcloud_load_balancer(name: attribute('id')) do
    it { should exist }
    its('load_balancer_type') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
