# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_volume/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudVolume
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_volume,
      attributes_class: Hcloud::Types::VolumeAttributes,
      outputs: { id: :id },
      map: [:name, :size],
      map_present: [:format, :labels, :location, :server_id],
      map_bool: [:automount, :delete_protection]
  end
  module Hcloud
    include HcloudVolume
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
