# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class VolumeAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :name, T::String
    attribute :size, (T::Coercible::Integer | T::Coercible::Float)
    attribute? :automount, T::Bool.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :format, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :location, T::String.optional
    attribute? :server_id, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
