# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class VolumeAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :name, T::String
    attribute :size, T::Float
    attribute? :automount, T::Bool.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :format, T::String.optional
    attribute? :labels, T::Hash.optional
  end
end
