# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_volume infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_volume/ -t hcloud://

control 'hcloud_volume-exists' do
  impact 1.0
  title 'Manages a hcloud_volume resource'
  desc 'Verify that the hcloud_volume resource exists and has expected properties'

  describe hcloud_volume(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
    its('size') { should_not be_nil }
  end
end
