# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_rdns/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudRdns
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_rdns,
      attributes_class: Hcloud::Types::RdnsAttributes,
      outputs: { id: :id },
      map: [:dns_ptr, :ip_address],
      map_present: [:floating_ip_id, :load_balancer_id, :primary_ip_id, :server_id]
  end
  module Hcloud
    include HcloudRdns
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
