# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class RdnsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :dns_ptr, T::String
    attribute :ip_address, T::String
    attribute? :floating_ip_id, T::Float.optional
    attribute? :load_balancer_id, T::Float.optional
    attribute? :primary_ip_id, T::Float.optional
    attribute? :server_id, T::Float.optional
  end
end
