# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class RdnsAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :dns_ptr, T::String
    attribute :ip_address, T::String
    attribute? :floating_ip_id, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :load_balancer_id, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :primary_ip_id, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :server_id, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
