# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_storage_box/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudStorageBox
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_storage_box,
      attributes_class: Hcloud::Types::StorageBoxAttributes,
      outputs: { id: :id },
      map: [:location, :name, :password, :storage_box_type],
      map_present: [:access_settings, :labels, :snapshot_plan, :ssh_keys],
      map_bool: [:delete_protection]
  end
  module Hcloud
    include HcloudStorageBox
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
