# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class StorageBoxAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :location, T::String
    attribute :name, T::String
    attribute :password, T::String
    attribute :storage_box_type, T::String
    attribute? :snapshot_plan, T::Hash.optional
  end
end
