# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class StorageBoxAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :location, T::String
    attribute :name, T::String
    attribute :password, T::String
    attribute :storage_box_type, T::String
    attribute? :access_settings, T::Hash.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :labels, T::Hash.optional
    attribute? :snapshot_plan, T::Hash.optional
    attribute? :ssh_keys, T::Array.of(T::String).optional
  end
end
