# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_placement_group infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_placement_group/ -t hcloud://

control 'hcloud_placement_group-exists' do
  impact 1.0
  title 'Manages a hcloud_placement_group resource'
  desc 'Verify that the hcloud_placement_group resource exists and has expected properties'

  describe hcloud_placement_group(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
    its('type') { should_not be_nil }
  end
end
