# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_network_subnet infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_network_subnet/ -t hcloud://

control 'hcloud_network_subnet-exists' do
  impact 1.0
  title 'Manages a hcloud_network_subnet resource'
  desc 'Verify that the hcloud_network_subnet resource exists and has expected properties'

  describe hcloud_network_subnet(name: attribute('id')) do
    it { should exist }
    its('ip_range') { should_not be_nil }
    its('network_id') { should_not be_nil }
    its('network_zone') { should_not be_nil }
    its('type') { should_not be_nil }
  end
end
