# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_zone/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudZone
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_zone,
      attributes_class: Hcloud::Types::ZoneAttributes,
      outputs: { id: :id },
      map: [:mode, :name]
  end
  module Hcloud
    include HcloudZone
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
