# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class ZoneAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :mode, T::String
    attribute :name, T::String
    attribute? :delete_protection, T::Bool.optional
    attribute? :labels, T::Hash.optional
    attribute? :primary_nameservers, T::Array.of(T::Hash).optional
    attribute? :ttl, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
