# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_load_balancer/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudLoadBalancer
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_load_balancer,
      attributes_class: Hcloud::Types::LoadBalancerAttributes,
      outputs: { id: :id },
      map: [:load_balancer_type, :name],
      map_present: [:algorithm, :labels, :location, :network_zone, :target],
      map_bool: [:delete_protection]
  end
  module Hcloud
    include HcloudLoadBalancer
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
