# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class LoadBalancerAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :load_balancer_type, T::String
    attribute :name, T::String
    attribute? :algorithm, T::Array.of(T::Hash).optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :target, T::Array.of(T::Hash).optional
  end
end
