# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class LoadBalancerAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :load_balancer_type, T::String
    attribute :name, T::String
    attribute? :algorithm, T::Hash.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :labels, T::Hash.optional
    attribute? :location, T::String.optional
    attribute? :network_zone, T::String.optional
    attribute? :target, T::Array.of(T::Hash).optional
  end
end
