# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_network_subnet/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudNetworkSubnet
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_network_subnet,
      attributes_class: Hcloud::Types::NetworkSubnetAttributes,
      outputs: { id: :id },
      map: [:ip_range, :network_id, :network_zone, :type],
      map_present: [:vswitch_id]
  end
  module Hcloud
    include HcloudNetworkSubnet
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
