# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class NetworkSubnetAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :ip_range, T::String
    attribute :network_id, T::Float
    attribute :network_zone, T::String
    attribute :type, T::String
    attribute? :vswitch_id, T::Float.optional
  end
end
