# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class NetworkSubnetAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :ip_range, T::String
    attribute :network_id, (T::Coercible::Integer | T::Coercible::Float)
    attribute :network_zone, T::String
    attribute :type, T::String
    attribute? :vswitch_id, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
