# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_firewall_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudFirewallAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_firewall_attachment,
      attributes_class: Hcloud::Types::FirewallAttachmentAttributes,
      outputs: { id: :id },
      map: [:firewall_id],
      map_present: [:label_selectors, :server_ids]
  end
  module Hcloud
    include HcloudFirewallAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
