# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class FirewallAttachmentAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :firewall_id, (T::Coercible::Integer | T::Coercible::Float)
    attribute? :label_selectors, T::Array.of(T::String).optional
    attribute? :server_ids, T::Array.of((T::Coercible::Integer | T::Coercible::Float)).optional
  end
end
