# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class FirewallAttachmentAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :firewall_id, T::Float
    attribute? :label_selectors, T::Array.of(T::String).optional
    attribute? :server_ids, T::Array.of(T::Float).optional
  end
end
