# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_uploaded_certificate/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudUploadedCertificate
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_uploaded_certificate,
      attributes_class: Hcloud::Types::UploadedCertificateAttributes,
      outputs: { id: :id },
      map: [:certificate, :name, :private_key],
      map_present: [:labels]
  end
  module Hcloud
    include HcloudUploadedCertificate
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
