# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class UploadedCertificateAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :certificate, T::String
    attribute :name, T::String
    attribute :private_key, T::String
    attribute? :labels, T::Hash.optional
  end
end
