# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class UploadedCertificateAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :certificate, T::String
    attribute :name, T::String
    attribute :private_key, T::String
    attribute? :labels, T::Hash.optional
  end
end
