# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_rdns infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_rdns/ -t hcloud://

control 'hcloud_rdns-exists' do
  impact 1.0
  title 'Manages a hcloud_rdns resource'
  desc 'Verify that the hcloud_rdns resource exists and has expected properties'

  describe hcloud_rdns(name: attribute('id')) do
    it { should exist }
    its('dns_ptr') { should_not be_nil }
    its('ip_address') { should_not be_nil }
  end
end
