# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_zone_rrset/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudZoneRrset
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_zone_rrset,
      attributes_class: Hcloud::Types::ZoneRrsetAttributes,
      outputs: { id: :id },
      map: [:name, :records, :type, :zone],
      map_present: [:labels, :ttl],
      map_bool: [:change_protection]
  end
  module Hcloud
    include HcloudZoneRrset
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
