# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class ZoneRrsetAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :name, T::String
    attribute :records, T::Array.of(T::Hash)
    attribute :type, T::String
    attribute :zone, T::String
    attribute? :change_protection, T::Bool.optional
    attribute? :labels, T::Hash.optional
    attribute? :ttl, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
