# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class ZoneRrsetAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :name, T::String
    attribute :records, T::Array.of(T::Hash)
    attribute :type, T::String
    attribute :zone, T::String
    attribute? :ttl, T::Float.optional
  end
end
