# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_managed_certificate/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudManagedCertificate
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_managed_certificate,
      attributes_class: Hcloud::Types::ManagedCertificateAttributes,
      outputs: { id: :id },
      map: [:domain_names, :name],
      map_present: [:labels]
  end
  module Hcloud
    include HcloudManagedCertificate
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
