# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_zone_record infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_zone_record/ -t hcloud://

control 'hcloud_zone_record-exists' do
  impact 1.0
  title 'Manages a hcloud_zone_record resource'
  desc 'Verify that the hcloud_zone_record resource exists and has expected properties'

  describe hcloud_zone_record(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
    its('type') { should_not be_nil }
    its('value') { should_not be_nil }
    its('zone') { should_not be_nil }
  end
end
