# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea-core'
require 'terraform-synthesizer'

module Pangea; module Resources; module Hcloud; module Types; end; end; end; end

# Hcloud resources
require_relative 'pangea/resources/hcloud_certificate/resource'
require_relative 'pangea/resources/hcloud_firewall/resource'
require_relative 'pangea/resources/hcloud_firewall_attachment/resource'
require_relative 'pangea/resources/hcloud_floating_ip/resource'
require_relative 'pangea/resources/hcloud_floating_ip_assignment/resource'
require_relative 'pangea/resources/hcloud_load_balancer/resource'
require_relative 'pangea/resources/hcloud_load_balancer_network/resource'
require_relative 'pangea/resources/hcloud_load_balancer_service/resource'
require_relative 'pangea/resources/hcloud_load_balancer_target/resource'
require_relative 'pangea/resources/hcloud_managed_certificate/resource'
require_relative 'pangea/resources/hcloud_network/resource'
require_relative 'pangea/resources/hcloud_network_route/resource'
require_relative 'pangea/resources/hcloud_network_subnet/resource'
require_relative 'pangea/resources/hcloud_placement_group/resource'
require_relative 'pangea/resources/hcloud_primary_ip/resource'
require_relative 'pangea/resources/hcloud_rdns/resource'
require_relative 'pangea/resources/hcloud_server/resource'
require_relative 'pangea/resources/hcloud_server_network/resource'
require_relative 'pangea/resources/hcloud_snapshot/resource'
require_relative 'pangea/resources/hcloud_ssh_key/resource'
require_relative 'pangea/resources/hcloud_storage_box/resource'
require_relative 'pangea/resources/hcloud_storage_box_snapshot/resource'
require_relative 'pangea/resources/hcloud_storage_box_subaccount/resource'
require_relative 'pangea/resources/hcloud_uploaded_certificate/resource'
require_relative 'pangea/resources/hcloud_volume/resource'
require_relative 'pangea/resources/hcloud_volume_attachment/resource'
require_relative 'pangea/resources/hcloud_zone/resource'
require_relative 'pangea/resources/hcloud_zone_record/resource'
require_relative 'pangea/resources/hcloud_zone_rrset/resource'

# Hcloud module aggregator
require_relative 'pangea/resources/hcloud'
