# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_network_route infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_network_route/ -t hcloud://

control 'hcloud_network_route-exists' do
  impact 1.0
  title 'Manages a hcloud_network_route resource'
  desc 'Verify that the hcloud_network_route resource exists and has expected properties'

  describe hcloud_network_route(name: attribute('id')) do
    it { should exist }
    its('destination') { should_not be_nil }
    its('gateway') { should_not be_nil }
    its('network_id') { should_not be_nil }
  end
end
