# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_network_route/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudNetworkRoute
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_network_route,
      attributes_class: Hcloud::Types::NetworkRouteAttributes,
      outputs: { id: :id },
      map: [:destination, :gateway, :network_id]
  end
  module Hcloud
    include HcloudNetworkRoute
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
