# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class NetworkRouteAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :destination, T::String
    attribute :gateway, T::String
    attribute :network_id, (T::Coercible::Integer | T::Coercible::Float)
  end
end
