# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_storage_box infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_storage_box/ -t hcloud://

control 'hcloud_storage_box-exists' do
  impact 1.0
  title 'Manages a hcloud_storage_box resource'
  desc 'Verify that the hcloud_storage_box resource exists and has expected properties'

  describe hcloud_storage_box(name: attribute('id')) do
    it { should exist }
    its('location') { should_not be_nil }
    its('name') { should_not be_nil }
    its('storage_box_type') { should_not be_nil }
  end
end
