# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_storage_box_snapshot/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudStorageBoxSnapshot
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_storage_box_snapshot,
      attributes_class: Hcloud::Types::StorageBoxSnapshotAttributes,
      outputs: { id: :id },
      map: [:storage_box_id]
  end
  module Hcloud
    include HcloudStorageBoxSnapshot
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
