# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_storage_box_snapshot infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_storage_box_snapshot/ -t hcloud://

control 'hcloud_storage_box_snapshot-exists' do
  impact 1.0
  title 'Manages a hcloud_storage_box_snapshot resource'
  desc 'Verify that the hcloud_storage_box_snapshot resource exists and has expected properties'

  describe hcloud_storage_box_snapshot(name: attribute('id')) do
    it { should exist }
    its('storage_box_id') { should_not be_nil }
  end
end
