# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_floating_ip infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_floating_ip/ -t hcloud://

control 'hcloud_floating_ip-exists' do
  impact 1.0
  title 'Manages a hcloud_floating_ip resource'
  desc 'Verify that the hcloud_floating_ip resource exists and has expected properties'

  describe hcloud_floating_ip(name: attribute('id')) do
    it { should exist }
    its('type') { should_not be_nil }
  end
end
