# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_load_balancer_network/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudLoadBalancerNetwork
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_load_balancer_network,
      attributes_class: Hcloud::Types::LoadBalancerNetworkAttributes,
      outputs: { id: :id },
      map: [:load_balancer_id],
      map_present: [:subnet_id]
  end
  module Hcloud
    include HcloudLoadBalancerNetwork
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
