# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class LoadBalancerNetworkAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :load_balancer_id, (T::Coercible::Integer | T::Coercible::Float)
    attribute? :enable_public_interface, T::Bool.optional
    attribute? :ip, T::String.optional
    attribute? :network_id, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :subnet_id, T::String.optional
  end
end
