# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_server/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudServer
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_server,
      attributes_class: Hcloud::Types::ServerAttributes,
      outputs: { id: :id },
      map: [:name, :server_type],
      map_present: [:datacenter, :firewall_ids, :image, :iso, :labels, :location, :network, :placement_group_id, :public_net, :rescue, :ssh_keys, :user_data],
      map_bool: [:allow_deprecated_images, :backups, :delete_protection, :ignore_remote_firewall_ids, :keep_disk, :rebuild_protection, :shutdown_before_deletion]
  end
  module Hcloud
    include HcloudServer
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
