# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class ServerAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :name, T::String
    attribute :server_type, T::String
    attribute? :allow_deprecated_images, T::Bool.optional
    attribute? :backups, T::Bool.optional
    attribute? :delete_protection, T::Bool.optional
    attribute? :ignore_remote_firewall_ids, T::Bool.optional
    attribute? :image, T::String.optional
    attribute? :iso, T::String.optional
    attribute? :keep_disk, T::Bool.optional
    attribute? :labels, T::Hash.optional
    attribute? :network, T::Array.of(T::Hash).optional
    attribute? :placement_group_id, T::Float.optional
    attribute? :public_net, T::Array.of(T::Hash).optional
    attribute? :rebuild_protection, T::Bool.optional
    attribute? :rescue, T::String.optional
    attribute? :shutdown_before_deletion, T::Bool.optional
    attribute? :ssh_keys, T::Array.of(T::String).optional
    attribute? :user_data, T::String.optional
  end
end
