# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_floating_ip_assignment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudFloatingIpAssignment
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_floating_ip_assignment,
      attributes_class: Hcloud::Types::FloatingIpAssignmentAttributes,
      outputs: { id: :id },
      map: [:floating_ip_id, :server_id]
  end
  module Hcloud
    include HcloudFloatingIpAssignment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
