# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_load_balancer_service infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_load_balancer_service/ -t hcloud://

control 'hcloud_load_balancer_service-exists' do
  impact 1.0
  title 'Manages a hcloud_load_balancer_service resource'
  desc 'Verify that the hcloud_load_balancer_service resource exists and has expected properties'

  describe hcloud_load_balancer_service(name: attribute('id')) do
    it { should exist }
    its('load_balancer_id') { should_not be_nil }
    its('protocol') { should_not be_nil }
  end
end
