# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_load_balancer_service/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudLoadBalancerService
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_load_balancer_service,
      attributes_class: Hcloud::Types::LoadBalancerServiceAttributes,
      outputs: { id: :id },
      map: [:load_balancer_id, :protocol],
      map_present: [:health_check, :http]
  end
  module Hcloud
    include HcloudLoadBalancerService
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
