# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class LoadBalancerServiceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :load_balancer_id, T::String
    attribute :protocol, T::String
    attribute? :health_check, T::Array.of(T::Hash).optional
    attribute? :http, T::Array.of(T::Hash).optional
  end
end
