# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class LoadBalancerServiceAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :load_balancer_id, T::String
    attribute :protocol, T::String
    attribute? :destination_port, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :health_check, T::Hash.optional
    attribute? :http, T::Hash.optional
    attribute? :listen_port, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :proxyprotocol, T::Bool.optional
  end
end
