# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_volume_attachment infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_volume_attachment/ -t hcloud://

control 'hcloud_volume_attachment-exists' do
  impact 1.0
  title 'Manages a hcloud_volume_attachment resource'
  desc 'Verify that the hcloud_volume_attachment resource exists and has expected properties'

  describe hcloud_volume_attachment(name: attribute('id')) do
    it { should exist }
    its('server_id') { should_not be_nil }
    its('volume_id') { should_not be_nil }
  end
end
