# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_storage_box_subaccount/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudStorageBoxSubaccount
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_storage_box_subaccount,
      attributes_class: Hcloud::Types::StorageBoxSubaccountAttributes,
      outputs: { id: :id },
      map: [:home_directory, :password, :storage_box_id],
      map_present: [:access_settings, :description, :labels, :name]
  end
  module Hcloud
    include HcloudStorageBoxSubaccount
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
