# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class StorageBoxSubaccountAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Hcloud::Types

    attribute :home_directory, T::String
    attribute :password, T::String
    attribute :storage_box_id, (T::Coercible::Integer | T::Coercible::Float)
    attribute? :access_settings, T::Hash.optional
    attribute? :description, T::String.optional
    attribute? :labels, T::Hash.optional
    attribute? :name, T::String.optional
  end
end
