# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class FirewallAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :name, T::String
    attribute? :apply_to, T::Array.of(T::Hash).optional
    attribute? :rule, T::Array.of(T::Hash).optional
  end
end
