# Code generated by pangea-forge.
# InSpec profile for verifying hcloud_firewall_attachment infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set HCLOUD_TOKEN and HCLOUD_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/hcloud_firewall_attachment/ -t hcloud://

control 'hcloud_firewall_attachment-exists' do
  impact 1.0
  title 'Manages a hcloud_firewall_attachment resource'
  desc 'Verify that the hcloud_firewall_attachment resource exists and has expected properties'

  describe hcloud_firewall_attachment(name: attribute('id')) do
    it { should exist }
    its('firewall_id') { should_not be_nil }
  end
end
