# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_load_balancer resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudLoadBalancer do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { load_balancer_type: 'test-value', name: 'test-value' } }

  describe ':hcloud_load_balancer' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_load_balancer', 'test')
        validate_required_attributes(config, [:load_balancer_type, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_load_balancer('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_load_balancer)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_load_balancer('test', required_attrs)

        expect(ref.id).to eq("${hcloud_load_balancer.test.id}")
        expect(ref.ipv4).to eq("${hcloud_load_balancer.test.ipv4}")
        expect(ref.ipv6).to eq("${hcloud_load_balancer.test.ipv6}")
        expect(ref.labels).to eq("${hcloud_load_balancer.test.labels}")
        expect(ref.location).to eq("${hcloud_load_balancer.test.location}")
        expect(ref.network_id).to eq("${hcloud_load_balancer.test.network_id}")
        expect(ref.network_ip).to eq("${hcloud_load_balancer.test.network_ip}")
        expect(ref.network_zone).to eq("${hcloud_load_balancer.test.network_zone}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_load_balancer', 'test')
        expect(config).not_to have_key('ipv4')
        expect(config).not_to have_key('ipv6')
        expect(config).not_to have_key('labels')
        expect(config).not_to have_key('location')
        expect(config).not_to have_key('network_id')
        expect(config).not_to have_key('network_ip')
        expect(config).not_to have_key('network_zone')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ algorithm: [{ 'key1' => 'val1' }], delete_protection: true, target: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_load_balancer', 'full')
        expect(config).to have_key('algorithm')
        expect(config).to have_key('delete_protection')
        expect(config).to have_key('target')
      end
    end

    context 'optional attributes' do
      it 'includes algorithm when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer('opt', required_attrs.merge(algorithm: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer', 'opt')
        expect(config).to have_key('algorithm')
      end

      it 'omits algorithm when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer', 'minimal')
        expect(config).not_to have_key('algorithm')
      end
      it 'includes delete_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer('opt', required_attrs.merge(delete_protection: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer', 'opt')
        expect(config).to have_key('delete_protection')
      end

      it 'omits delete_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer', 'minimal')
        expect(config).not_to have_key('delete_protection')
      end
      it 'includes target when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer('opt', required_attrs.merge(target: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer', 'opt')
        expect(config).to have_key('target')
      end

      it 'omits target when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer', 'minimal')
        expect(config).not_to have_key('target')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts delete_protection=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(delete_protection: val)
          synth.hcloud_load_balancer("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_load_balancer', "bool_#{val}")
          expect(config['delete_protection']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_load_balancer', 'typed')
        expect(config['load_balancer_type']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer('first', required_attrs)
        synth.hcloud_load_balancer('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_load_balancer')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_load_balancer,
    method: :hcloud_load_balancer,
    required_attrs: { load_balancer_type: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :ipv4, :ipv6, :labels, :location, :network_id, :network_ip, :network_zone],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:delete_protection]
end
