# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_load_balancer_service resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudLoadBalancerService do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { load_balancer_id: 'test-value', protocol: 'test-value' } }

  describe ':hcloud_load_balancer_service' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_service('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_load_balancer_service', 'test')
        validate_required_attributes(config, [:load_balancer_id, :protocol])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_load_balancer_service('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_load_balancer_service)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_load_balancer_service('test', required_attrs)

        expect(ref.id).to eq("${hcloud_load_balancer_service.test.id}")
        expect(ref.destination_port).to eq("${hcloud_load_balancer_service.test.destination_port}")
        expect(ref.listen_port).to eq("${hcloud_load_balancer_service.test.listen_port}")
        expect(ref.proxyprotocol).to eq("${hcloud_load_balancer_service.test.proxyprotocol}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_service('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_load_balancer_service', 'test')
        expect(config).not_to have_key('destination_port')
        expect(config).not_to have_key('listen_port')
        expect(config).not_to have_key('proxyprotocol')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ health_check: [{ 'key1' => 'val1' }], http: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_service('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_load_balancer_service', 'full')
        expect(config).to have_key('health_check')
        expect(config).to have_key('http')
      end
    end

    context 'optional attributes' do
      it 'includes health_check when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_service('opt', required_attrs.merge(health_check: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_service', 'opt')
        expect(config).to have_key('health_check')
      end

      it 'omits health_check when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_service', 'minimal')
        expect(config).not_to have_key('health_check')
      end
      it 'includes http when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_service('opt', required_attrs.merge(http: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_service', 'opt')
        expect(config).to have_key('http')
      end

      it 'omits http when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_service('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_service', 'minimal')
        expect(config).not_to have_key('http')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_service('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_load_balancer_service', 'typed')
        expect(config['load_balancer_id']).to be_a(String)
        expect(config['protocol']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_service('first', required_attrs)
        synth.hcloud_load_balancer_service('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_load_balancer_service')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_load_balancer_service,
    method: :hcloud_load_balancer_service,
    required_attrs: { load_balancer_id: 'test-value', protocol: 'test-value' },
    expected_outputs: [:id, :destination_port, :listen_port, :proxyprotocol],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
