# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_firewall_attachment resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudFirewallAttachment do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { firewall_id: 3.14 } }

  describe ':hcloud_firewall_attachment' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall_attachment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_firewall_attachment', 'test')
        validate_required_attributes(config, [:firewall_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_firewall_attachment('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_firewall_attachment)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_firewall_attachment('test', required_attrs)

        expect(ref.id).to eq("${hcloud_firewall_attachment.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ label_selectors: ['test-value'], server_ids: [3.14] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall_attachment('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_firewall_attachment', 'full')
        expect(config).to have_key('label_selectors')
        expect(config).to have_key('server_ids')
      end
    end

    context 'optional attributes' do
      it 'includes label_selectors when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall_attachment('opt', required_attrs.merge(label_selectors: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_firewall_attachment', 'opt')
        expect(config).to have_key('label_selectors')
      end

      it 'omits label_selectors when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall_attachment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_firewall_attachment', 'minimal')
        expect(config).not_to have_key('label_selectors')
      end
      it 'includes server_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall_attachment('opt', required_attrs.merge(server_ids: [3.14]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_firewall_attachment', 'opt')
        expect(config).to have_key('server_ids')
      end

      it 'omits server_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall_attachment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_firewall_attachment', 'minimal')
        expect(config).not_to have_key('server_ids')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall_attachment('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_firewall_attachment', 'typed')
        expect(config['firewall_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall_attachment('first', required_attrs)
        synth.hcloud_firewall_attachment('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_firewall_attachment')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_firewall_attachment,
    method: :hcloud_firewall_attachment,
    required_attrs: { firewall_id: 3.14 },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
