# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_storage_box_subaccount resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudStorageBoxSubaccount do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { home_directory: 'test-value', password: 'test-value', storage_box_id: 3.14 } }

  describe ':hcloud_storage_box_subaccount' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box_subaccount('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_storage_box_subaccount', 'test')
        validate_required_attributes(config, [:home_directory, :password, :storage_box_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_storage_box_subaccount('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_storage_box_subaccount)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_storage_box_subaccount('test', required_attrs)

        expect(ref.id).to eq("${hcloud_storage_box_subaccount.test.id}")
        expect(ref.access_settings).to eq("${hcloud_storage_box_subaccount.test.access_settings}")
        expect(ref.description).to eq("${hcloud_storage_box_subaccount.test.description}")
        expect(ref.labels).to eq("${hcloud_storage_box_subaccount.test.labels}")
        expect(ref.name).to eq("${hcloud_storage_box_subaccount.test.name}")
        expect(ref.server).to eq("${hcloud_storage_box_subaccount.test.server}")
        expect(ref.username).to eq("${hcloud_storage_box_subaccount.test.username}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box_subaccount('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_storage_box_subaccount', 'test')
        expect(config).not_to have_key('access_settings')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('labels')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('server')
        expect(config).not_to have_key('username')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:password]
        expect(sensitive_fields).to include(:password)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box_subaccount('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_storage_box_subaccount', 'typed')
        expect(config['home_directory']).to be_a(String)
        expect(config['password']).to be_a(String)
        expect(config['storage_box_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box_subaccount('first', required_attrs)
        synth.hcloud_storage_box_subaccount('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_storage_box_subaccount')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_storage_box_subaccount,
    method: :hcloud_storage_box_subaccount,
    required_attrs: { home_directory: 'test-value', password: 'test-value', storage_box_id: 3.14 },
    expected_outputs: [:id, :access_settings, :description, :labels, :name, :server, :username],
    sensitive_fields: [:password],
    immutable_fields: [],
    boolean_fields: []
end
