# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_zone resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudZone do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { mode: 'test-value', name: 'test-value' } }

  describe ':hcloud_zone' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_zone', 'test')
        validate_required_attributes(config, [:mode, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_zone('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_zone)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_zone('test', required_attrs)

        expect(ref.id).to eq("${hcloud_zone.test.id}")
        expect(ref.authoritative_nameservers).to eq("${hcloud_zone.test.authoritative_nameservers}")
        expect(ref.delete_protection).to eq("${hcloud_zone.test.delete_protection}")
        expect(ref.labels).to eq("${hcloud_zone.test.labels}")
        expect(ref.primary_nameservers).to eq("${hcloud_zone.test.primary_nameservers}")
        expect(ref.registrar).to eq("${hcloud_zone.test.registrar}")
        expect(ref.ttl).to eq("${hcloud_zone.test.ttl}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_zone', 'test')
        expect(config).not_to have_key('authoritative_nameservers')
        expect(config).not_to have_key('delete_protection')
        expect(config).not_to have_key('labels')
        expect(config).not_to have_key('primary_nameservers')
        expect(config).not_to have_key('registrar')
        expect(config).not_to have_key('ttl')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_zone', 'typed')
        expect(config['mode']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone('first', required_attrs)
        synth.hcloud_zone('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_zone')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_zone,
    method: :hcloud_zone,
    required_attrs: { mode: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :authoritative_nameservers, :delete_protection, :labels, :primary_nameservers, :registrar, :ttl],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
