# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_rdns resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudRdns do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { dns_ptr: 'test-value', ip_address: 'test-value' } }

  describe ':hcloud_rdns' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_rdns('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_rdns', 'test')
        validate_required_attributes(config, [:dns_ptr, :ip_address])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_rdns('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_rdns)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_rdns('test', required_attrs)

        expect(ref.id).to eq("${hcloud_rdns.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ floating_ip_id: 3.14, load_balancer_id: 3.14, primary_ip_id: 3.14, server_id: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_rdns('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_rdns', 'full')
        expect(config).to have_key('floating_ip_id')
        expect(config).to have_key('load_balancer_id')
        expect(config).to have_key('primary_ip_id')
        expect(config).to have_key('server_id')
      end
    end

    context 'optional attributes' do
      it 'includes floating_ip_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_rdns('opt', required_attrs.merge(floating_ip_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_rdns', 'opt')
        expect(config).to have_key('floating_ip_id')
      end

      it 'omits floating_ip_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_rdns('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_rdns', 'minimal')
        expect(config).not_to have_key('floating_ip_id')
      end
      it 'includes load_balancer_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_rdns('opt', required_attrs.merge(load_balancer_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_rdns', 'opt')
        expect(config).to have_key('load_balancer_id')
      end

      it 'omits load_balancer_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_rdns('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_rdns', 'minimal')
        expect(config).not_to have_key('load_balancer_id')
      end
      it 'includes primary_ip_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_rdns('opt', required_attrs.merge(primary_ip_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_rdns', 'opt')
        expect(config).to have_key('primary_ip_id')
      end

      it 'omits primary_ip_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_rdns('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_rdns', 'minimal')
        expect(config).not_to have_key('primary_ip_id')
      end
      it 'includes server_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_rdns('opt', required_attrs.merge(server_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_rdns', 'opt')
        expect(config).to have_key('server_id')
      end

      it 'omits server_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_rdns('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_rdns', 'minimal')
        expect(config).not_to have_key('server_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_rdns('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_rdns', 'typed')
        expect(config['dns_ptr']).to be_a(String)
        expect(config['ip_address']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_rdns('first', required_attrs)
        synth.hcloud_rdns('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_rdns')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_rdns,
    method: :hcloud_rdns,
    required_attrs: { dns_ptr: 'test-value', ip_address: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
