# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_load_balancer_target resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudLoadBalancerTarget do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { load_balancer_id: 3.14, type: 'test-value' } }

  describe ':hcloud_load_balancer_target' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_target('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_load_balancer_target', 'test')
        validate_required_attributes(config, [:load_balancer_id, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_load_balancer_target('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_load_balancer_target)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_load_balancer_target('test', required_attrs)

        expect(ref.id).to eq("${hcloud_load_balancer_target.test.id}")
        expect(ref.use_private_ip).to eq("${hcloud_load_balancer_target.test.use_private_ip}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_target('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_load_balancer_target', 'test')
        expect(config).not_to have_key('use_private_ip')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ ip: 'test-value', label_selector: 'test-value', server_id: 3.14, use_private_ip: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_target('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_load_balancer_target', 'full')
        expect(config).to have_key('ip')
        expect(config).to have_key('label_selector')
        expect(config).to have_key('server_id')
        expect(config).to have_key('use_private_ip')
      end
    end

    context 'optional attributes' do
      it 'includes ip when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_target('opt', required_attrs.merge(ip: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_target', 'opt')
        expect(config).to have_key('ip')
      end

      it 'omits ip when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_target('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_target', 'minimal')
        expect(config).not_to have_key('ip')
      end
      it 'includes label_selector when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_target('opt', required_attrs.merge(label_selector: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_target', 'opt')
        expect(config).to have_key('label_selector')
      end

      it 'omits label_selector when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_target('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_target', 'minimal')
        expect(config).not_to have_key('label_selector')
      end
      it 'includes server_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_target('opt', required_attrs.merge(server_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_target', 'opt')
        expect(config).to have_key('server_id')
      end

      it 'omits server_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_target('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_target', 'minimal')
        expect(config).not_to have_key('server_id')
      end
      it 'includes use_private_ip when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_target('opt', required_attrs.merge(use_private_ip: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_target', 'opt')
        expect(config).to have_key('use_private_ip')
      end

      it 'omits use_private_ip when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_target('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_target', 'minimal')
        expect(config).not_to have_key('use_private_ip')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts use_private_ip=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(use_private_ip: val)
          synth.hcloud_load_balancer_target("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_load_balancer_target', "bool_#{val}")
          expect(config['use_private_ip']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_target('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_load_balancer_target', 'typed')
        expect(config['load_balancer_id']).to be_a(Float)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_target('first', required_attrs)
        synth.hcloud_load_balancer_target('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_load_balancer_target')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_load_balancer_target,
    method: :hcloud_load_balancer_target,
    required_attrs: { load_balancer_id: 3.14, type: 'test-value' },
    expected_outputs: [:id, :use_private_ip],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:use_private_ip]
end
