# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_firewall resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudFirewall do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':hcloud_firewall' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_firewall', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_firewall('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_firewall)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_firewall('test', required_attrs)

        expect(ref.id).to eq("${hcloud_firewall.test.id}")
        expect(ref.labels).to eq("${hcloud_firewall.test.labels}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_firewall', 'test')
        expect(config).not_to have_key('labels')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ apply_to: [{ 'key1' => 'val1' }], rule: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_firewall', 'full')
        expect(config).to have_key('apply_to')
        expect(config).to have_key('rule')
      end
    end

    context 'optional attributes' do
      it 'includes apply_to when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall('opt', required_attrs.merge(apply_to: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_firewall', 'opt')
        expect(config).to have_key('apply_to')
      end

      it 'omits apply_to when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_firewall', 'minimal')
        expect(config).not_to have_key('apply_to')
      end
      it 'includes rule when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall('opt', required_attrs.merge(rule: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_firewall', 'opt')
        expect(config).to have_key('rule')
      end

      it 'omits rule when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_firewall', 'minimal')
        expect(config).not_to have_key('rule')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_firewall', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_firewall('first', required_attrs)
        synth.hcloud_firewall('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_firewall')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_firewall,
    method: :hcloud_firewall,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :labels],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
