# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_storage_box resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudStorageBox do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { location: 'test-value', name: 'test-value', password: 'test-value', storage_box_type: 'test-value' } }

  describe ':hcloud_storage_box' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_storage_box', 'test')
        validate_required_attributes(config, [:location, :name, :password, :storage_box_type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_storage_box('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_storage_box)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_storage_box('test', required_attrs)

        expect(ref.id).to eq("${hcloud_storage_box.test.id}")
        expect(ref.access_settings).to eq("${hcloud_storage_box.test.access_settings}")
        expect(ref.delete_protection).to eq("${hcloud_storage_box.test.delete_protection}")
        expect(ref.labels).to eq("${hcloud_storage_box.test.labels}")
        expect(ref.server).to eq("${hcloud_storage_box.test.server}")
        expect(ref.ssh_keys).to eq("${hcloud_storage_box.test.ssh_keys}")
        expect(ref.system).to eq("${hcloud_storage_box.test.system}")
        expect(ref.username).to eq("${hcloud_storage_box.test.username}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_storage_box', 'test')
        expect(config).not_to have_key('access_settings')
        expect(config).not_to have_key('delete_protection')
        expect(config).not_to have_key('labels')
        expect(config).not_to have_key('server')
        expect(config).not_to have_key('ssh_keys')
        expect(config).not_to have_key('system')
        expect(config).not_to have_key('username')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ access_settings: { 'key1' => 'val1' }, delete_protection: true, labels: { 'key1' => 'val1' }, snapshot_plan: { 'key1' => 'val1' }, ssh_keys: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_storage_box', 'full')
        expect(config).to have_key('access_settings')
        expect(config).to have_key('delete_protection')
        expect(config).to have_key('labels')
        expect(config).to have_key('snapshot_plan')
        expect(config).to have_key('ssh_keys')
      end
    end

    context 'optional attributes' do
      it 'includes access_settings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('opt', required_attrs.merge(access_settings: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_storage_box', 'opt')
        expect(config).to have_key('access_settings')
      end

      it 'omits access_settings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_storage_box', 'minimal')
        expect(config).not_to have_key('access_settings')
      end
      it 'includes delete_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('opt', required_attrs.merge(delete_protection: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_storage_box', 'opt')
        expect(config).to have_key('delete_protection')
      end

      it 'omits delete_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_storage_box', 'minimal')
        expect(config).not_to have_key('delete_protection')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_storage_box', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_storage_box', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes snapshot_plan when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('opt', required_attrs.merge(snapshot_plan: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_storage_box', 'opt')
        expect(config).to have_key('snapshot_plan')
      end

      it 'omits snapshot_plan when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_storage_box', 'minimal')
        expect(config).not_to have_key('snapshot_plan')
      end
      it 'includes ssh_keys when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('opt', required_attrs.merge(ssh_keys: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_storage_box', 'opt')
        expect(config).to have_key('ssh_keys')
      end

      it 'omits ssh_keys when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_storage_box', 'minimal')
        expect(config).not_to have_key('ssh_keys')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:password]
        expect(sensitive_fields).to include(:password)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts delete_protection=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(delete_protection: val)
          synth.hcloud_storage_box("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_storage_box', "bool_#{val}")
          expect(config['delete_protection']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_storage_box', 'typed')
        expect(config['location']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['password']).to be_a(String)
        expect(config['storage_box_type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box('first', required_attrs)
        synth.hcloud_storage_box('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_storage_box')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_storage_box,
    method: :hcloud_storage_box,
    required_attrs: { location: 'test-value', name: 'test-value', password: 'test-value', storage_box_type: 'test-value' },
    expected_outputs: [:id, :access_settings, :delete_protection, :labels, :server, :ssh_keys, :system, :username],
    sensitive_fields: [:password],
    immutable_fields: [],
    boolean_fields: [:delete_protection]
end
