# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_floating_ip_assignment resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudFloatingIpAssignment do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { floating_ip_id: 3.14, server_id: 3.14 } }

  describe ':hcloud_floating_ip_assignment' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_floating_ip_assignment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_floating_ip_assignment', 'test')
        validate_required_attributes(config, [:floating_ip_id, :server_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_floating_ip_assignment('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_floating_ip_assignment)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_floating_ip_assignment('test', required_attrs)

        expect(ref.id).to eq("${hcloud_floating_ip_assignment.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_floating_ip_assignment('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_floating_ip_assignment', 'typed')
        expect(config['floating_ip_id']).to be_a(Float)
        expect(config['server_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_floating_ip_assignment('first', required_attrs)
        synth.hcloud_floating_ip_assignment('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_floating_ip_assignment')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_floating_ip_assignment,
    method: :hcloud_floating_ip_assignment,
    required_attrs: { floating_ip_id: 3.14, server_id: 3.14 },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
