# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_network_subnet resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudNetworkSubnet do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { ip_range: 'test-value', network_id: 3.14, network_zone: 'test-value', type: 'test-value' } }

  describe ':hcloud_network_subnet' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_network_subnet('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_network_subnet', 'test')
        validate_required_attributes(config, [:ip_range, :network_id, :network_zone, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_network_subnet('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_network_subnet)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_network_subnet('test', required_attrs)

        expect(ref.id).to eq("${hcloud_network_subnet.test.id}")
        expect(ref.gateway).to eq("${hcloud_network_subnet.test.gateway}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_network_subnet('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_network_subnet', 'test')
        expect(config).not_to have_key('gateway')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ vswitch_id: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_network_subnet('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_network_subnet', 'full')
        expect(config).to have_key('vswitch_id')
      end
    end

    context 'optional attributes' do
      it 'includes vswitch_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_network_subnet('opt', required_attrs.merge(vswitch_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_network_subnet', 'opt')
        expect(config).to have_key('vswitch_id')
      end

      it 'omits vswitch_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_network_subnet('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_network_subnet', 'minimal')
        expect(config).not_to have_key('vswitch_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_network_subnet('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_network_subnet', 'typed')
        expect(config['ip_range']).to be_a(String)
        expect(config['network_id']).to be_a(Float)
        expect(config['network_zone']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_network_subnet('first', required_attrs)
        synth.hcloud_network_subnet('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_network_subnet')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_network_subnet,
    method: :hcloud_network_subnet,
    required_attrs: { ip_range: 'test-value', network_id: 3.14, network_zone: 'test-value', type: 'test-value' },
    expected_outputs: [:id, :gateway],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
