# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_volume resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudVolume do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', size: 3.14 } }

  describe ':hcloud_volume' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_volume', 'test')
        validate_required_attributes(config, [:name, :size])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_volume('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_volume)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_volume('test', required_attrs)

        expect(ref.id).to eq("${hcloud_volume.test.id}")
        expect(ref.linux_device).to eq("${hcloud_volume.test.linux_device}")
        expect(ref.location).to eq("${hcloud_volume.test.location}")
        expect(ref.server_id).to eq("${hcloud_volume.test.server_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_volume', 'test')
        expect(config).not_to have_key('linux_device')
        expect(config).not_to have_key('location')
        expect(config).not_to have_key('server_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ automount: true, delete_protection: true, format: 'test-value', labels: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_volume', 'full')
        expect(config).to have_key('automount')
        expect(config).to have_key('delete_protection')
        expect(config).to have_key('format')
        expect(config).to have_key('labels')
      end
    end

    context 'optional attributes' do
      it 'includes automount when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume('opt', required_attrs.merge(automount: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_volume', 'opt')
        expect(config).to have_key('automount')
      end

      it 'omits automount when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_volume', 'minimal')
        expect(config).not_to have_key('automount')
      end
      it 'includes delete_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume('opt', required_attrs.merge(delete_protection: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_volume', 'opt')
        expect(config).to have_key('delete_protection')
      end

      it 'omits delete_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_volume', 'minimal')
        expect(config).not_to have_key('delete_protection')
      end
      it 'includes format when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume('opt', required_attrs.merge(format: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_volume', 'opt')
        expect(config).to have_key('format')
      end

      it 'omits format when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_volume', 'minimal')
        expect(config).not_to have_key('format')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_volume', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_volume', 'minimal')
        expect(config).not_to have_key('labels')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts automount=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(automount: val)
          synth.hcloud_volume("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_volume', "bool_#{val}")
          expect(config['automount']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts delete_protection=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(delete_protection: val)
          synth.hcloud_volume("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_volume', "bool_#{val}")
          expect(config['delete_protection']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_volume', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['size']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume('first', required_attrs)
        synth.hcloud_volume('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_volume')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_volume,
    method: :hcloud_volume,
    required_attrs: { name: 'test-value', size: 3.14 },
    expected_outputs: [:id, :linux_device, :location, :server_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:automount, :delete_protection]
end
