# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_load_balancer_network resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudLoadBalancerNetwork do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { load_balancer_id: 3.14 } }

  describe ':hcloud_load_balancer_network' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_network('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_load_balancer_network', 'test')
        validate_required_attributes(config, [:load_balancer_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_load_balancer_network('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_load_balancer_network)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_load_balancer_network('test', required_attrs)

        expect(ref.id).to eq("${hcloud_load_balancer_network.test.id}")
        expect(ref.enable_public_interface).to eq("${hcloud_load_balancer_network.test.enable_public_interface}")
        expect(ref.ip).to eq("${hcloud_load_balancer_network.test.ip}")
        expect(ref.network_id).to eq("${hcloud_load_balancer_network.test.network_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_network('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_load_balancer_network', 'test')
        expect(config).not_to have_key('enable_public_interface')
        expect(config).not_to have_key('ip')
        expect(config).not_to have_key('network_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ enable_public_interface: true, ip: 'test-value', network_id: 3.14, subnet_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_network('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_load_balancer_network', 'full')
        expect(config).to have_key('enable_public_interface')
        expect(config).to have_key('ip')
        expect(config).to have_key('network_id')
        expect(config).to have_key('subnet_id')
      end
    end

    context 'optional attributes' do
      it 'includes enable_public_interface when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_network('opt', required_attrs.merge(enable_public_interface: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_network', 'opt')
        expect(config).to have_key('enable_public_interface')
      end

      it 'omits enable_public_interface when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_network('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_network', 'minimal')
        expect(config).not_to have_key('enable_public_interface')
      end
      it 'includes ip when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_network('opt', required_attrs.merge(ip: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_network', 'opt')
        expect(config).to have_key('ip')
      end

      it 'omits ip when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_network('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_network', 'minimal')
        expect(config).not_to have_key('ip')
      end
      it 'includes network_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_network('opt', required_attrs.merge(network_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_network', 'opt')
        expect(config).to have_key('network_id')
      end

      it 'omits network_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_network('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_network', 'minimal')
        expect(config).not_to have_key('network_id')
      end
      it 'includes subnet_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_network('opt', required_attrs.merge(subnet_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_network', 'opt')
        expect(config).to have_key('subnet_id')
      end

      it 'omits subnet_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_network('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_load_balancer_network', 'minimal')
        expect(config).not_to have_key('subnet_id')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enable_public_interface=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_public_interface: val)
          synth.hcloud_load_balancer_network("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_load_balancer_network', "bool_#{val}")
          expect(config['enable_public_interface']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_network('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_load_balancer_network', 'typed')
        expect(config['load_balancer_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_load_balancer_network('first', required_attrs)
        synth.hcloud_load_balancer_network('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_load_balancer_network')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_load_balancer_network,
    method: :hcloud_load_balancer_network,
    required_attrs: { load_balancer_id: 3.14 },
    expected_outputs: [:id, :enable_public_interface, :ip, :network_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enable_public_interface]
end
