# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_zone_record resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudZoneRecord do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', type: 'test-value', value: 'test-value', zone: 'test-value' } }

  describe ':hcloud_zone_record' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_record('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_zone_record', 'test')
        validate_required_attributes(config, [:name, :type, :value, :zone])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_zone_record('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_zone_record)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_zone_record('test', required_attrs)

        expect(ref.id).to eq("${hcloud_zone_record.test.id}")
        expect(ref.comment).to eq("${hcloud_zone_record.test.comment}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_record('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_zone_record', 'test')
        expect(config).not_to have_key('comment')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comment: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_record('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_zone_record', 'full')
        expect(config).to have_key('comment')
      end
    end

    context 'optional attributes' do
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_record('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_zone_record', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_record('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_zone_record', 'minimal')
        expect(config).not_to have_key('comment')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_record('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_zone_record', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['type']).to be_a(String)
        expect(config['value']).to be_a(String)
        expect(config['zone']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_record('first', required_attrs)
        synth.hcloud_zone_record('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_zone_record')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_zone_record,
    method: :hcloud_zone_record,
    required_attrs: { name: 'test-value', type: 'test-value', value: 'test-value', zone: 'test-value' },
    expected_outputs: [:id, :comment],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
