# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_server_network resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudServerNetwork do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { server_id: 3.14 } }

  describe ':hcloud_server_network' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server_network('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_server_network', 'test')
        validate_required_attributes(config, [:server_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_server_network('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_server_network)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_server_network('test', required_attrs)

        expect(ref.id).to eq("${hcloud_server_network.test.id}")
        expect(ref.alias_ips).to eq("${hcloud_server_network.test.alias_ips}")
        expect(ref.ip).to eq("${hcloud_server_network.test.ip}")
        expect(ref.mac_address).to eq("${hcloud_server_network.test.mac_address}")
        expect(ref.network_id).to eq("${hcloud_server_network.test.network_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server_network('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_server_network', 'test')
        expect(config).not_to have_key('alias_ips')
        expect(config).not_to have_key('ip')
        expect(config).not_to have_key('mac_address')
        expect(config).not_to have_key('network_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ alias_ips: ['test-value'], ip: 'test-value', network_id: 3.14, subnet_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server_network('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_server_network', 'full')
        expect(config).to have_key('alias_ips')
        expect(config).to have_key('ip')
        expect(config).to have_key('network_id')
        expect(config).to have_key('subnet_id')
      end
    end

    context 'optional attributes' do
      it 'includes alias_ips when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server_network('opt', required_attrs.merge(alias_ips: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server_network', 'opt')
        expect(config).to have_key('alias_ips')
      end

      it 'omits alias_ips when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server_network('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server_network', 'minimal')
        expect(config).not_to have_key('alias_ips')
      end
      it 'includes ip when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server_network('opt', required_attrs.merge(ip: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server_network', 'opt')
        expect(config).to have_key('ip')
      end

      it 'omits ip when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server_network('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server_network', 'minimal')
        expect(config).not_to have_key('ip')
      end
      it 'includes network_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server_network('opt', required_attrs.merge(network_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server_network', 'opt')
        expect(config).to have_key('network_id')
      end

      it 'omits network_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server_network('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server_network', 'minimal')
        expect(config).not_to have_key('network_id')
      end
      it 'includes subnet_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server_network('opt', required_attrs.merge(subnet_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server_network', 'opt')
        expect(config).to have_key('subnet_id')
      end

      it 'omits subnet_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server_network('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server_network', 'minimal')
        expect(config).not_to have_key('subnet_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server_network('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_server_network', 'typed')
        expect(config['server_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server_network('first', required_attrs)
        synth.hcloud_server_network('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_server_network')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_server_network,
    method: :hcloud_server_network,
    required_attrs: { server_id: 3.14 },
    expected_outputs: [:id, :alias_ips, :ip, :mac_address, :network_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
