# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_volume_attachment resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudVolumeAttachment do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { server_id: 3.14, volume_id: 3.14 } }

  describe ':hcloud_volume_attachment' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume_attachment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_volume_attachment', 'test')
        validate_required_attributes(config, [:server_id, :volume_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_volume_attachment('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_volume_attachment)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_volume_attachment('test', required_attrs)

        expect(ref.id).to eq("${hcloud_volume_attachment.test.id}")
        expect(ref.automount).to eq("${hcloud_volume_attachment.test.automount}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume_attachment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_volume_attachment', 'test')
        expect(config).not_to have_key('automount')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume_attachment('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_volume_attachment', 'typed')
        expect(config['server_id']).to be_a(Float)
        expect(config['volume_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_volume_attachment('first', required_attrs)
        synth.hcloud_volume_attachment('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_volume_attachment')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_volume_attachment,
    method: :hcloud_volume_attachment,
    required_attrs: { server_id: 3.14, volume_id: 3.14 },
    expected_outputs: [:id, :automount],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
