# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_storage_box_snapshot resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudStorageBoxSnapshot do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { storage_box_id: 3.14 } }

  describe ':hcloud_storage_box_snapshot' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box_snapshot('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_storage_box_snapshot', 'test')
        validate_required_attributes(config, [:storage_box_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_storage_box_snapshot('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_storage_box_snapshot)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_storage_box_snapshot('test', required_attrs)

        expect(ref.id).to eq("${hcloud_storage_box_snapshot.test.id}")
        expect(ref.description).to eq("${hcloud_storage_box_snapshot.test.description}")
        expect(ref.is_automatic).to eq("${hcloud_storage_box_snapshot.test.is_automatic}")
        expect(ref.labels).to eq("${hcloud_storage_box_snapshot.test.labels}")
        expect(ref.name).to eq("${hcloud_storage_box_snapshot.test.name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box_snapshot('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_storage_box_snapshot', 'test')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('is_automatic')
        expect(config).not_to have_key('labels')
        expect(config).not_to have_key('name')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box_snapshot('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_storage_box_snapshot', 'typed')
        expect(config['storage_box_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_storage_box_snapshot('first', required_attrs)
        synth.hcloud_storage_box_snapshot('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_storage_box_snapshot')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_storage_box_snapshot,
    method: :hcloud_storage_box_snapshot,
    required_attrs: { storage_box_id: 3.14 },
    expected_outputs: [:id, :description, :is_automatic, :labels, :name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
