# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_zone_rrset resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudZoneRrset do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', records: [{ 'key1' => 'val1' }], type: 'test-value', zone: 'test-value' } }

  describe ':hcloud_zone_rrset' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_rrset('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_zone_rrset', 'test')
        validate_required_attributes(config, [:name, :records, :type, :zone])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_zone_rrset('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_zone_rrset)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_zone_rrset('test', required_attrs)

        expect(ref.id).to eq("${hcloud_zone_rrset.test.id}")
        expect(ref.change_protection).to eq("${hcloud_zone_rrset.test.change_protection}")
        expect(ref.labels).to eq("${hcloud_zone_rrset.test.labels}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_rrset('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_zone_rrset', 'test')
        expect(config).not_to have_key('change_protection')
        expect(config).not_to have_key('labels')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ change_protection: true, labels: { 'key1' => 'val1' }, ttl: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_rrset('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_zone_rrset', 'full')
        expect(config).to have_key('change_protection')
        expect(config).to have_key('labels')
        expect(config).to have_key('ttl')
      end
    end

    context 'optional attributes' do
      it 'includes change_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_rrset('opt', required_attrs.merge(change_protection: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_zone_rrset', 'opt')
        expect(config).to have_key('change_protection')
      end

      it 'omits change_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_rrset('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_zone_rrset', 'minimal')
        expect(config).not_to have_key('change_protection')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_rrset('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_zone_rrset', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_rrset('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_zone_rrset', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_rrset('opt', required_attrs.merge(ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_zone_rrset', 'opt')
        expect(config).to have_key('ttl')
      end

      it 'omits ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_rrset('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_zone_rrset', 'minimal')
        expect(config).not_to have_key('ttl')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts change_protection=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(change_protection: val)
          synth.hcloud_zone_rrset("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_zone_rrset', "bool_#{val}")
          expect(config['change_protection']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_rrset('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_zone_rrset', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['records']).to be_a(Array)
        expect(config['type']).to be_a(String)
        expect(config['zone']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_zone_rrset('first', required_attrs)
        synth.hcloud_zone_rrset('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_zone_rrset')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_zone_rrset,
    method: :hcloud_zone_rrset,
    required_attrs: { name: 'test-value', records: [{ 'key1' => 'val1' }], type: 'test-value', zone: 'test-value' },
    expected_outputs: [:id, :change_protection, :labels],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:change_protection]
end
