# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_ssh_key resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudSshKey do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', public_key: 'test-value' } }

  describe ':hcloud_ssh_key' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_ssh_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_ssh_key', 'test')
        validate_required_attributes(config, [:name, :public_key])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_ssh_key('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_ssh_key)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_ssh_key('test', required_attrs)

        expect(ref.id).to eq("${hcloud_ssh_key.test.id}")
        expect(ref.fingerprint).to eq("${hcloud_ssh_key.test.fingerprint}")
        expect(ref.labels).to eq("${hcloud_ssh_key.test.labels}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_ssh_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_ssh_key', 'test')
        expect(config).not_to have_key('fingerprint')
        expect(config).not_to have_key('labels')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ labels: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_ssh_key('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_ssh_key', 'full')
        expect(config).to have_key('labels')
      end
    end

    context 'optional attributes' do
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_ssh_key('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_ssh_key', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_ssh_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_ssh_key', 'minimal')
        expect(config).not_to have_key('labels')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_ssh_key('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_ssh_key', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['public_key']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_ssh_key('first', required_attrs)
        synth.hcloud_ssh_key('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_ssh_key')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_ssh_key,
    method: :hcloud_ssh_key,
    required_attrs: { name: 'test-value', public_key: 'test-value' },
    expected_outputs: [:id, :fingerprint, :labels],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
