# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_server resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudServer do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', server_type: 'test-value' } }

  describe ':hcloud_server' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_server', 'test')
        validate_required_attributes(config, [:name, :server_type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_server('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_server)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_server('test', required_attrs)

        expect(ref.id).to eq("${hcloud_server.test.id}")
        expect(ref.backup_window).to eq("${hcloud_server.test.backup_window}")
        expect(ref.datacenter).to eq("${hcloud_server.test.datacenter}")
        expect(ref.firewall_ids).to eq("${hcloud_server.test.firewall_ids}")
        expect(ref.ipv4_address).to eq("${hcloud_server.test.ipv4_address}")
        expect(ref.ipv6_address).to eq("${hcloud_server.test.ipv6_address}")
        expect(ref.ipv6_network).to eq("${hcloud_server.test.ipv6_network}")
        expect(ref.location).to eq("${hcloud_server.test.location}")
        expect(ref.primary_disk_size).to eq("${hcloud_server.test.primary_disk_size}")
        expect(ref.status).to eq("${hcloud_server.test.status}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_server', 'test')
        expect(config).not_to have_key('backup_window')
        expect(config).not_to have_key('datacenter')
        expect(config).not_to have_key('firewall_ids')
        expect(config).not_to have_key('ipv4_address')
        expect(config).not_to have_key('ipv6_address')
        expect(config).not_to have_key('ipv6_network')
        expect(config).not_to have_key('location')
        expect(config).not_to have_key('primary_disk_size')
        expect(config).not_to have_key('status')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allow_deprecated_images: true, backups: true, datacenter: 'test-value', delete_protection: true, firewall_ids: [3.14], ignore_remote_firewall_ids: true, image: 'test-value', iso: 'test-value', keep_disk: true, labels: { 'key1' => 'val1' }, location: 'test-value', network: [{ 'key1' => 'val1' }], placement_group_id: 3.14, public_net: [{ 'key1' => 'val1' }], rebuild_protection: true, rescue: 'test-value', shutdown_before_deletion: true, ssh_keys: ['test-value'], user_data: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_server', 'full')
        expect(config).to have_key('allow_deprecated_images')
        expect(config).to have_key('backups')
        expect(config).to have_key('datacenter')
        expect(config).to have_key('delete_protection')
        expect(config).to have_key('firewall_ids')
        expect(config).to have_key('ignore_remote_firewall_ids')
        expect(config).to have_key('image')
        expect(config).to have_key('iso')
        expect(config).to have_key('keep_disk')
        expect(config).to have_key('labels')
        expect(config).to have_key('location')
        expect(config).to have_key('network')
        expect(config).to have_key('placement_group_id')
        expect(config).to have_key('public_net')
        expect(config).to have_key('rebuild_protection')
        expect(config).to have_key('rescue')
        expect(config).to have_key('shutdown_before_deletion')
        expect(config).to have_key('ssh_keys')
        expect(config).to have_key('user_data')
      end
    end

    context 'optional attributes' do
      it 'includes allow_deprecated_images when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(allow_deprecated_images: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('allow_deprecated_images')
      end

      it 'omits allow_deprecated_images when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('allow_deprecated_images')
      end
      it 'includes backups when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(backups: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('backups')
      end

      it 'omits backups when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('backups')
      end
      it 'includes datacenter when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(datacenter: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('datacenter')
      end

      it 'omits datacenter when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('datacenter')
      end
      it 'includes delete_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(delete_protection: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('delete_protection')
      end

      it 'omits delete_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('delete_protection')
      end
      it 'includes firewall_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(firewall_ids: [3.14]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('firewall_ids')
      end

      it 'omits firewall_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('firewall_ids')
      end
      it 'includes ignore_remote_firewall_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(ignore_remote_firewall_ids: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('ignore_remote_firewall_ids')
      end

      it 'omits ignore_remote_firewall_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('ignore_remote_firewall_ids')
      end
      it 'includes image when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(image: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('image')
      end

      it 'omits image when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('image')
      end
      it 'includes iso when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(iso: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('iso')
      end

      it 'omits iso when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('iso')
      end
      it 'includes keep_disk when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(keep_disk: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('keep_disk')
      end

      it 'omits keep_disk when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('keep_disk')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes location when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(location: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('location')
      end

      it 'omits location when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('location')
      end
      it 'includes network when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(network: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('network')
      end

      it 'omits network when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('network')
      end
      it 'includes placement_group_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(placement_group_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('placement_group_id')
      end

      it 'omits placement_group_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('placement_group_id')
      end
      it 'includes public_net when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(public_net: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('public_net')
      end

      it 'omits public_net when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('public_net')
      end
      it 'includes rebuild_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(rebuild_protection: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('rebuild_protection')
      end

      it 'omits rebuild_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('rebuild_protection')
      end
      it 'includes rescue when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(rescue: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('rescue')
      end

      it 'omits rescue when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('rescue')
      end
      it 'includes shutdown_before_deletion when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(shutdown_before_deletion: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('shutdown_before_deletion')
      end

      it 'omits shutdown_before_deletion when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('shutdown_before_deletion')
      end
      it 'includes ssh_keys when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(ssh_keys: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('ssh_keys')
      end

      it 'omits ssh_keys when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('ssh_keys')
      end
      it 'includes user_data when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('opt', required_attrs.merge(user_data: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'opt')
        expect(config).to have_key('user_data')
      end

      it 'omits user_data when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_server', 'minimal')
        expect(config).not_to have_key('user_data')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts allow_deprecated_images=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_deprecated_images: val)
          synth.hcloud_server("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_server', "bool_#{val}")
          expect(config['allow_deprecated_images']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts backups=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(backups: val)
          synth.hcloud_server("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_server', "bool_#{val}")
          expect(config['backups']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts delete_protection=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(delete_protection: val)
          synth.hcloud_server("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_server', "bool_#{val}")
          expect(config['delete_protection']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts ignore_remote_firewall_ids=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ignore_remote_firewall_ids: val)
          synth.hcloud_server("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_server', "bool_#{val}")
          expect(config['ignore_remote_firewall_ids']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts keep_disk=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(keep_disk: val)
          synth.hcloud_server("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_server', "bool_#{val}")
          expect(config['keep_disk']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts rebuild_protection=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(rebuild_protection: val)
          synth.hcloud_server("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_server', "bool_#{val}")
          expect(config['rebuild_protection']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts shutdown_before_deletion=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(shutdown_before_deletion: val)
          synth.hcloud_server("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_server', "bool_#{val}")
          expect(config['shutdown_before_deletion']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_server', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['server_type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_server('first', required_attrs)
        synth.hcloud_server('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_server')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_server,
    method: :hcloud_server,
    required_attrs: { name: 'test-value', server_type: 'test-value' },
    expected_outputs: [:id, :backup_window, :datacenter, :firewall_ids, :ipv4_address, :ipv6_address, :ipv6_network, :location, :primary_disk_size, :status],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:allow_deprecated_images, :backups, :delete_protection, :ignore_remote_firewall_ids, :keep_disk, :rebuild_protection, :shutdown_before_deletion]
end
