# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_floating_ip resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudFloatingIp do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { type: 'test-value' } }

  describe ':hcloud_floating_ip' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_floating_ip('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_floating_ip', 'test')
        validate_required_attributes(config, [:type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_floating_ip('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_floating_ip)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_floating_ip('test', required_attrs)

        expect(ref.id).to eq("${hcloud_floating_ip.test.id}")
        expect(ref.home_location).to eq("${hcloud_floating_ip.test.home_location}")
        expect(ref.ip_address).to eq("${hcloud_floating_ip.test.ip_address}")
        expect(ref.ip_network).to eq("${hcloud_floating_ip.test.ip_network}")
        expect(ref.name).to eq("${hcloud_floating_ip.test.name}")
        expect(ref.server_id).to eq("${hcloud_floating_ip.test.server_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_floating_ip('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_floating_ip', 'test')
        expect(config).not_to have_key('home_location')
        expect(config).not_to have_key('ip_address')
        expect(config).not_to have_key('ip_network')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('server_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ delete_protection: true, description: 'test-value', labels: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_floating_ip('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_floating_ip', 'full')
        expect(config).to have_key('delete_protection')
        expect(config).to have_key('description')
        expect(config).to have_key('labels')
      end
    end

    context 'optional attributes' do
      it 'includes delete_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_floating_ip('opt', required_attrs.merge(delete_protection: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_floating_ip', 'opt')
        expect(config).to have_key('delete_protection')
      end

      it 'omits delete_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_floating_ip('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_floating_ip', 'minimal')
        expect(config).not_to have_key('delete_protection')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_floating_ip('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_floating_ip', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_floating_ip('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_floating_ip', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_floating_ip('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_floating_ip', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_floating_ip('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_floating_ip', 'minimal')
        expect(config).not_to have_key('labels')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts delete_protection=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(delete_protection: val)
          synth.hcloud_floating_ip("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'hcloud_floating_ip', "bool_#{val}")
          expect(config['delete_protection']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_floating_ip('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_floating_ip', 'typed')
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_floating_ip('first', required_attrs)
        synth.hcloud_floating_ip('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_floating_ip')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_floating_ip,
    method: :hcloud_floating_ip,
    required_attrs: { type: 'test-value' },
    expected_outputs: [:id, :home_location, :ip_address, :ip_network, :name, :server_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:delete_protection]
end
