# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a hcloud_managed_certificate resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::HcloudManagedCertificate do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { domain_names: ['test-value'], name: 'test-value' } }

  describe ':hcloud_managed_certificate' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_managed_certificate('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'hcloud_managed_certificate', 'test')
        validate_required_attributes(config, [:domain_names, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_managed_certificate('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:hcloud_managed_certificate)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.hcloud_managed_certificate('test', required_attrs)

        expect(ref.id).to eq("${hcloud_managed_certificate.test.id}")
        expect(ref.certificate).to eq("${hcloud_managed_certificate.test.certificate}")
        expect(ref.created).to eq("${hcloud_managed_certificate.test.created}")
        expect(ref.fingerprint).to eq("${hcloud_managed_certificate.test.fingerprint}")
        expect(ref.not_valid_after).to eq("${hcloud_managed_certificate.test.not_valid_after}")
        expect(ref.not_valid_before).to eq("${hcloud_managed_certificate.test.not_valid_before}")
        expect(ref.type).to eq("${hcloud_managed_certificate.test.type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_managed_certificate('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_managed_certificate', 'test')
        expect(config).not_to have_key('certificate')
        expect(config).not_to have_key('created')
        expect(config).not_to have_key('fingerprint')
        expect(config).not_to have_key('not_valid_after')
        expect(config).not_to have_key('not_valid_before')
        expect(config).not_to have_key('type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ labels: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_managed_certificate('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_managed_certificate', 'full')
        expect(config).to have_key('labels')
      end
    end

    context 'optional attributes' do
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_managed_certificate('opt', required_attrs.merge(labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_managed_certificate', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_managed_certificate('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'hcloud_managed_certificate', 'minimal')
        expect(config).not_to have_key('labels')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_managed_certificate('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'hcloud_managed_certificate', 'typed')
        expect(config['domain_names']).to be_a(Array)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.hcloud_managed_certificate('first', required_attrs)
        synth.hcloud_managed_certificate('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'hcloud_managed_certificate')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :hcloud_managed_certificate,
    method: :hcloud_managed_certificate,
    required_attrs: { domain_names: ['test-value'], name: 'test-value' },
    expected_outputs: [:id, :certificate, :created, :fingerprint, :not_valid_after, :not_valid_before, :type],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
