# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/hcloud_ssh_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module HcloudSshKey
    include Pangea::Resources::ResourceBuilder

    define_resource :hcloud_ssh_key,
      attributes_class: Hcloud::Types::SshKeyAttributes,
      outputs: { id: :id },
      map: [:name, :public_key],
      map_present: [:labels]
  end
  module Hcloud
    include HcloudSshKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Hcloud)
