# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Hcloud::Types
  include Dry.Types()

  class SshKeyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Hcloud::Types

    attribute :name, T::String
    attribute :public_key, T::String
  end
end
